---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox

inputs:
- name: ci

outputs:
- name: new_version

run:
  path: cp
  args: ["version/number", "new_version/version"]