---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox

inputs:
- name: ci
- name: version

outputs:
- name: new_version

run:
  path: sh
  args:
  - "-c"
  - |
    cat version/number > new_version/number