---
platform: linux


image_resource:
  type: docker-image
  source:
    repository: busybox

inputs:
- name: ci
# - name: new_version


params:
  USERNAME:
  PASSWORD:
  # NEW_VERSION:


run:
  # path: ci/tasks/fly/fly.sh
  path: sh
  args:
  - "ci/tasks/fly/fly.sh"
