---
platform: linux


image_resource:
  type: docker-image
  source:
    repository: busybox

inputs:
- name: ci


params:
  USERNAME:
  PASSWORD:
  NEW_VERSION:


run:
  #path: ./ci/tasks/fly/fly.sh
  path: /bin/ls
  args:
  - "-l"
  - "ci/"
