---
platform: linux


image_resource:
  type: docker-image
  source:
    repository: busybox

inputs:
- name: ci


params:
  USERNAME:
  PASSWORD:
  NEW_VERSION:


run:
#  path: sh ci/tasks/fly/fly.sh
  path: sh
  args:
  - "ci/tasks/fly/fly.sh"
