---
anchors:
  notify-slack: &notify-slack
    on_failure:
      do:
      - put: notify
        inputs: ['ci-repo', 'bosh-states', 'bosh-creds']
        params:
          alert_type: failed
    on_error:
      do:
      - put: notify
        inputs: ['ci-repo', 'bosh-states', 'bosh-creds']
        params:
          alert_type: failed          

groups:
- name: full
  jobs:
  - terraform-plan
  - terraform-apply
  - BOSH
  - terraform-destroy
  - configure-UAA
  - BOSH-delete-env
  - CREDHUB
  - Download concourse release
  - CONCOURSE
- name: artefacts
  jobs:
  - Download concourse release
- name: deploy
  jobs:
  - terraform-plan
  - terraform-apply
  - BOSH
  - configure-UAA
  - CREDHUB
  - CONCOURSE
- name: delete
  jobs:
  - terraform-destroy
  - BOSH-delete-env     

resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: latest

- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

- name: slack-alert
  type: docker-image
  source:
    repository: arbourd/concourse-slack-alert-resource    

- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: every-day
  type: time
  source:
    interval: 24h

- name: notify
  type: slack-alert
  source:
    url: ((slack.webhook))
  icon: slack

- name: ci-repo
  type: git
  source:
    uri: ((github.url)):((github.user))/((github.repo)).git
    branch: feat/run-local-ci
    private_key: ((github_key))
    paths:
    - platform
  icon: git

- name: ci-image
  type: docker-image
  source: 
    repository: bzhtux/pivotal
    tag: debian
  icon: docker

- name: terraform
  type: terraform
  source:
    backend_type: gcs
    backend_config:
      bucket: bzhtux-tf-state
      prefix: concourse/((env_name))
      credentials: ((gcp.credentials))
  icon: docker

- name: gcp-creds
  type: gcs
  source:
      bucket: gcp-creds
      regexp: concourse-(.*).json
      json_key: ((gcp.credentials))
  icon: harddisk

- name: concourse-pivnet
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: p-concourse
    product_version: ((concourse-release-version))
  icon: cloud

- name: concourse-release
  type: gcs
  source:
      bucket: concourse
      regexp: ((env_name))/releases/concourse-bosh-release-(.*).tgz
      json_key: ((gcp.credentials))
  icon: harddisk

- name: concourse-config
  type: gcs
  source:
      bucket: concourse
      regexp: ((env_name))/config/((iaas))
      json_key: ((gcp.credentials))
  icon: harddisk

- name: bosh-states
  type: gcs
  source:
      bucket: bosh-states
      regexp: mgmt/((env_name))/state-(.*).json
      json_key: ((gcp.credentials))
  icon: harddisk

- name: bosh-creds
  type: gcs
  source:
      bucket: bosh-creds
      regexp: mgmt/((env_name))/creds-(.*).json
      json_key: ((gcp.credentials))
  icon: harddisk

jobs:
- name: Download concourse release
  plan:
  - in_parallel:
    - get: every-day
      trigger: true
    - get: concourse-pivnet
  - put: concourse-release
    inputs:
      - concourse-pivnet
    params:
      file: concourse-pivnet/concourse-bosh-release-((p-concourse-version)).tgz

- name: terraform-plan
  plan:
  - in_parallel:
    - get: ci-repo
      <<: *notify-slack
    - get: ci-image
      <<: *notify-slack
    - get: gcp-creds
      <<: *notify-slack
  - put: terraform
    params:
      env_name: ((env_name))
      iaas: ((iaas))
      plan_only: true
      terraform_source: ci-repo/platform/concourse/terraform/((iaas))
      vars:
        gcp_creds: ((gcp.credentials))
        ssh_pub_key: ((ssh.pub_key))
        ssh_user: ((ssh.user)) 
        ssh_priv_key: ((ssh.priv_key))
    <<: *notify-slack

- name: terraform-apply
  plan:
    - get: ci-repo
      <<: *notify-slack
    - get: ci-image
      <<: *notify-slack
    - get: gcp-creds
      <<: *notify-slack
    - get: terraform
      trigger: true
      passed: [terraform-plan]
    - put: terraform
      params:
        env_name: ((env_name))
        iaas: ((iaas))
        plan_run: true
        terraform_source: ci-repo/platform/concourse/terraform/((iaas))
        env:
          TF_LOG: DEBUG        
        vars:
          gcp_creds: ((gcp.credentials))   
          ssh_pub_key: ((ssh.pub_key)) 
          ssh_user: ((ssh.user)) 
          ssh_priv_key: ((ssh.priv_key))
      <<: *notify-slack

- name: terraform-destroy
  plan:
    - get: ci-repo
      <<: *notify-slack
    - get: terraform
      trigger: false
      passed: [terraform-apply]
    - put: terraform
      params:
        action: destroy
        env_name: ((env_name))        
        iaas: ((iaas))  
        terraform_source: ci-repo/platform/concourse/terraform/((iaas))
        env:
          TF_LOG: INFO                  
        vars:
          gcp_creds: ((gcp.credentials))
          ssh_pub_key: ((ssh.pub_key))
          ssh_user: ((ssh.user)) 
          ssh_priv_key: ((ssh.priv_key))     
      get_params:
        action: destroy
      <<: *notify-slack

- name: BOSH
  plan:
  - in_parallel:
    - get: ci-repo
      <<: *notify-slack
    - get: ci-image
      <<: *notify-slack
    - get: terraform
      trigger: true
      passed: [terraform-apply]
  - task: deploy
    image: ci-image
    file: "ci-repo/platform/bosh/ci/task.yml"
    params:
      SSH_PRIV_KEY: ((ssh.priv_key))
      SSH_USERNAME: ((ssh.user))
    <<: *notify-slack
  - put: bosh-states
    inputs: [bosh-state]
    params:
      file: bosh-state/state-*.json
  - put: bosh-creds
    inputs: [bosh-creds]
    params:
      file: bosh-creds/creds-*.yml

- name: configure-UAA
  plan:
  - in_parallel:
    - get: ci-repo
      <<: *notify-slack
    - get: ci-image
      <<: *notify-slack
    - get: terraform
      trigger: true
      passed: [BOSH]      
  - task: configure uaa for credhub deployment
    image: ci-image
    file: "ci-repo/platform/uaa/ci/credhub.yml"

- name: BOSH-delete-env
  plan:
  - in_parallel:
    - get: ci-repo
      <<: *notify-slack
    - get: ci-image
      <<: *notify-slack
    - get: terraform
      trigger: true
      passed: [BOSH]
    - get: bosh-states
      <<: *notify-slack
    - get: bosh-creds
      <<: *notify-slack
  - task: deploy
    image: ci-image
    file: "ci-repo/platform/bosh/ci/delete.yml"
    input_mapping:
      state: bosh-states
      creds: bosh-creds

    params:
      SSH_PRIV_KEY: ((ssh.priv_key))
      SSH_USERNAME: ((ssh.user))
    <<: *notify-slack

- name: CREDHUB
  plan:
  - in_parallel:
    - get: ci-repo
      <<: *notify-slack
    - get: ci-image
      <<: *notify-slack
    - get: terraform
      trigger: true
      passed: [configure-UAA]
  - task: deploy
    image: ci-image
    file: "ci-repo/platform/credhub/ci/task.yml"
    params:
      SSH_PRIV_KEY: ((ssh.priv_key))
      SSH_USERNAME: ((ssh.user))
    <<: *notify-slack

- name: CONCOURSE
  plan:
  - in_parallel:
    - get: ci-repo
      <<: *notify-slack
    - get: ci-image
      <<: *notify-slack
    - get: terraform
      trigger: true
      passed: [CREDHUB]
    - get: concourse-config
  - task: deploy
    image: ci-image
    file: "ci-repo/platform/concourse/ci/task.yml"
    params:
      SSH_PRIV_KEY: ((ssh.priv_key))
      SSH_USERNAME: ((ssh.user))
    <<: *notify-slack