---
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: latest

resources:
- name: ci-repo
  type: git
  source:
    uri: ((github.url)):((github.user))/((github.repo)).git
    branch: master
    private_key: ((github.key))
    paths:
    - platform
  icon: git

- name: ci-image
  type: docker-image
  source: 
    repository: bzhtux/pivotal:latest
  icon: docker

- name: terraform
  type: terraform
  source:
    backend_type: gcs
    backend_config:
        bucket: bzhtux-tf-state
        prefix: concourse/((cp))/terraform.tfstate
        region: europe-west6
        credentials: ((gcp.credentials))
    vars:
      tag_name: concourse
    env:
      AWS_ACCESS_KEY_ID: {{environment_access_key}}
      AWS_SECRET_ACCESS_KEY: {{environment_secret_key}}

jobs:
- name: terraform
  plan:
  - in_parallel:
    - get: ci-repo
    - get: ci-image
    - get: terraform