---
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: latest

- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: ci-repo
  type: git
  source:
    uri: ((github.url)):((github.user))/((github.repo)).git
    branch: feat/run-local-ci
    private_key: ((github_key))
    paths:
    - platform
  icon: git

- name: ci-image
  type: docker-image
  source: 
    repository: bzhtux/pivotal
  icon: docker

- name: terraform
  type: terraform
  source:
    backend_type: gcs
    backend_config:
      bucket: bzhtux-tf-state
      prefix: concourse/((cp))/terraform.tfstate
      credentials: ((gcp.credentials))
  icon: docker

- name: gcp-creds
  type: gcs
  source:
      bucket: gcp-creds
      regexp: service-account-(.*).json
      json_key: ((gcp.credentials))
  icon: github-circle

jobs:
- name: terraform-plan
  plan:
  - in_parallel:
    - get: ci-repo
    - get: ci-image
    - get: gcp-creds
  - task: list-creds
    image: ci-image
    config:
      platform: linux
      inputs:
      - name: gcp-creds
      run:
        path: sh
        args:
        - -exec
        - |
          ls -l gcp-creds/
  - put: terraform
    params:
      env_name: ((cp))
      plan_only: true
      terraform_source: ci-repo/platform/concourse/terraform/((cp))
      vars:
        gcp_creds: ((gcp.credentials))

- name: terraform-apply
  plan:
    - get: ci-repo
    - get: ci-image
    - get: gcp-creds
    - get: terraform
      trigger: false
      passed: [terraform-plan]
    - put: terraform
      params:
        env_name: ((cp))
        plan_run: true
        terraform_source: ci-repo/platform/concourse/terraform/((cp))
        vars:
          gcp_creds: ((gcp.credentials))        

- name: terraform-destroy
  plan:
    - get: ci-repo
    - put: terraform
      params:
        action: destroy
        env_name: ((cp))          
        terraform_source: ci-repo/platform/concourse/terraform/((cp))
        vars:
          gcp_creds: ((gcp.credentials))
      get_params:
        action: destroy