---
resources:
- name: version
  type: semver
  source:
    driver: git
    uri: https://github.com/bzhtux/sandbox.git
    branch: master
    initial_version: '0.0.1'
    file: concourse_repipe_version
- name: ci
  type: git
  source:
    uri: https://github.com/bzhtux/sandbox.git
    branch: master

jobs:
- name: update-version-tmp
  serial: true
  plan:
  - get: version
    trigger: true
  - get: ci
    trigger: true
  - task: get-version
    file: ci/tasks/version/version.yml
  - task: re-fly
    file: ci/tasks/fly/fly.yml
    params:
      USERNAME: ((username))
      PASSWORD: ((password))
      NEW_VERSION: new_version
