---
resources:
- name: version
  type: semver
  source:
    driver: git
    uri: https://github.com/bzhtux/sandbox.git
    branch: master
    initial_version: '0.0.1'
    file: concourse_repipe_version
- name: ci
  type: git
  source:
    uri: https://github.com/bzhtux/sandbox.git
    branch: master

jobs:
- name: update-version-tmp
  serial: true
  plan:
  - get: version
    trigger: true
  - get: ci
    trigger: true
  - task: display-version2
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}      
      inputs:
      - name: version
      run:
        path: ls
        args: ["version"]
  # - task: debug
  #   config:
  #     platform: linux
  #     image_resource:
  #       type: docker-image
  #       source: {repository: busybox}
  #     inputs:
  #       - name: ci
  #       - name: new_version
  #     run:
  #       path: cat
  #       args:
  #         - "-e"
  #         - "ci/tasks/fly/fly.sh"
  - task: re-fly
    file: ci/tasks/fly/fly.yml
    params:
      USERNAME: ((username))
      PASSWORD: ((password))
      NEW_VERSION: new_version
