---
jobs:
- name: display-version
  plan:
  - task: hello-version
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: echo
        args: [((version))]